name: e2e-tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment Failed Test On PR # triggers on test failure
        if: ${{ github.event_name == 'pull_request'}}
        run: |
          git clone --branch v0.1.0 https://github.com/operator-framework/flake-analyzer.git
          cd ./flake-analyzer
          make report-on-pr OWNER=operator-framework REPO=operator-lifecycle-manager TOKEN=${FLAKE_BOT_SEC} TEST_SUITE=e2e-test-output PR=1626


      
