name: e2e-tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo e2e-test-output-${{(github.event.pull_request.head.number)}}-${{ github.run_id }}

      
